//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AshleyInventoryUpdatedStatus.AshleyATP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/ATPRequest_AWS/ATPService", ConfigurationName="AshleyATP.ATPServiceSoap")]
    public interface ATPServiceSoap {
        
        // CODEGEN: Generating message contract since element name ExternalID from namespace http://tempuri.org/ATPRequest_AWS/ATPService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ATPRequest_AWS/ATPService/ATPRequest", ReplyAction="*")]
        AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestResponse ATPRequest(AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ATPRequest_AWS/ATPService/ATPRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestResponse> ATPRequestAsync(AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ATPRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ATPRequest", Namespace="http://tempuri.org/ATPRequest_AWS/ATPService", Order=0)]
        public AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequestBody Body;
        
        public ATPRequestRequest() {
        }
        
        public ATPRequestRequest(AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/ATPRequest_AWS/ATPService")]
    public partial class ATPRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExternalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string KeyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sXml;
        
        public ATPRequestRequestBody() {
        }
        
        public ATPRequestRequestBody(string ExternalID, string KeyCode, string sUser, string sPassword, string sXml) {
            this.ExternalID = ExternalID;
            this.KeyCode = KeyCode;
            this.sUser = sUser;
            this.sPassword = sPassword;
            this.sXml = sXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ATPRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ATPRequestResponse", Namespace="http://tempuri.org/ATPRequest_AWS/ATPService", Order=0)]
        public AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestResponseBody Body;
        
        public ATPRequestResponse() {
        }
        
        public ATPRequestResponse(AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/ATPRequest_AWS/ATPService")]
    public partial class ATPRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ATPRequestResult;
        
        public ATPRequestResponseBody() {
        }
        
        public ATPRequestResponseBody(string ATPRequestResult) {
            this.ATPRequestResult = ATPRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ATPServiceSoapChannel : AshleyInventoryUpdatedStatus.AshleyATP.ATPServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATPServiceSoapClient : System.ServiceModel.ClientBase<AshleyInventoryUpdatedStatus.AshleyATP.ATPServiceSoap>, AshleyInventoryUpdatedStatus.AshleyATP.ATPServiceSoap {
        
        public ATPServiceSoapClient() {
        }
        
        public ATPServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATPServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATPServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATPServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestResponse AshleyInventoryUpdatedStatus.AshleyATP.ATPServiceSoap.ATPRequest(AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequest request) {
            return base.Channel.ATPRequest(request);
        }
        
        public string ATPRequest(string ExternalID, string KeyCode, string sUser, string sPassword, string sXml) {
            AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequest inValue = new AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequest();
            inValue.Body = new AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequestBody();
            inValue.Body.ExternalID = ExternalID;
            inValue.Body.KeyCode = KeyCode;
            inValue.Body.sUser = sUser;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sXml = sXml;
            AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestResponse retVal = ((AshleyInventoryUpdatedStatus.AshleyATP.ATPServiceSoap)(this)).ATPRequest(inValue);
            return retVal.Body.ATPRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestResponse> AshleyInventoryUpdatedStatus.AshleyATP.ATPServiceSoap.ATPRequestAsync(AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequest request) {
            return base.Channel.ATPRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestResponse> ATPRequestAsync(string ExternalID, string KeyCode, string sUser, string sPassword, string sXml) {
            AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequest inValue = new AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequest();
            inValue.Body = new AshleyInventoryUpdatedStatus.AshleyATP.ATPRequestRequestBody();
            inValue.Body.ExternalID = ExternalID;
            inValue.Body.KeyCode = KeyCode;
            inValue.Body.sUser = sUser;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sXml = sXml;
            return ((AshleyInventoryUpdatedStatus.AshleyATP.ATPServiceSoap)(this)).ATPRequestAsync(inValue);
        }
    }
}
